export const pythonQuestions = [
  // O'zgaruvchilar, ma'lumot turlari, operatorlar (1-10)
  {
    id: 1,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nx = 5\ny = '10'\nresult = x + int(y)\nprint(result)\n```",
    options: ["A) 15", "B) 510", "C) TypeError", "D) 5"],
    correctAnswer: "A) 15",
  },
  {
    id: 2,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar", 
    type: "closed",
    question: "Quyidagilardan qaysi biri noto'g'ri o'zgaruvchi nomi?",
    options: ["A) _name", "B) name123", "C) 123name", "D) name_test"],
    correctAnswer: "C) 123name",
  },
  {
    id: 3,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed", 
    question: "Quyidagi kod natijasini toping:\n\n```python\nmy_dict = {'a': 1, 'b': 2}\ntype(my_dict)\n```",
    options: ["A) <class 'list'>", "B) <class 'dict'>", "C) <class 'tuple'>", "D) <class 'set'>"],
    correctAnswer: "B) <class 'dict'>",
  },
  {
    id: 4,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: 'Quyidagi kod natijasini toping:\n\n```python\ntext = "programming"\nlen(text[1::3])\n```',
    options: ["A) 3", "B) 4", "C) 2", "D) 5"],
    correctAnswer: "B) 4",
  },
  {
    id: 5,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\na = True\nb = False\nresult = not (a and b) or b\nprint(result)\n```",
    options: ["A) True", "B) False", "C) None", "D) Error"],
    correctAnswer: "A) True",
  },
  {
    id: 6,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kodlardan qaysi biri tuple yaratadi?",
    options: ["A) {1, 2, 3}", "B) [1, 2, 3]", "C) (1, 2, 3)", "D) {'a': 1}"],
    correctAnswer: "C) (1, 2, 3)",
  },
  {
    id: 7,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod chiqadigan qiymatni toping:\n\n```python\nprint(17 % 5)\n```",
    options: ["A) 3", "B) 2", "C) 4", "D) 1"],
    correctAnswer: "B) 2",
  },
  {
    id: 8,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nx = 4\ny = 2\nz = x ** y + x // y\nprint(z)\n```",
    options: ["A) 16", "B) 18", "C) 20", "D) 8"],
    correctAnswer: "B) 18",
  },
  {
    id: 9,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nmy_list = [1, 2, 3]\nmy_list.append(4)\nmy_list[2] = 10\nprint(my_list)\n```",
    options: ["A) [1, 2, 3, 4]", "B) [1, 2, 10, 4]", "C) [1, 2, 10]", "D) Error"],
    correctAnswer: "B) [1, 2, 10, 4]",
  },
  {
    id: 10,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kodda qanday xatolik bo'ladi?\n\n```python\nage = '25'\nresult = age + 5\n```",
    options: ["A) SyntaxError", "B) TypeError", "C) ValueError", "D) NameError"],
    correctAnswer: "B) TypeError",
  },

  // Shart operatorlari, sikllar, range() (11-20)
  {
    id: 11,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi kod nechta son chop etadi?\n\n```python\nfor i in range(2, 8, 2):\n    print(i)\n```",
    options: ["A) 2 ta", "B) 3 ta", "C) 4 ta", "D) 6 ta"],
    correctAnswer: "B) 3 ta",
  },
{
  id: 12,
  category: "Shart operatorlari, mantiqiy ifodalar",
  type: "closed",
  question: "Quyidagi kodda `print()` funksiyasi bajariladimi?\n\n```python\nif [] or 0 or None:\n    print('Executed')\nelse:\n    print('Not executed')\n```",
  options: [
    "A) Executed",
    "B) Not executed",
    "C) Xatolik beradi",
    "D) Faqat Python 3 da ishlaydi"
  ],
  correctAnswer: "B) Not executed"
},

  {
    id: 13,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi kod nechta qiymat beradi?\n\n```python\nlist(range(5, 20, 4))\n```",
    options: ["A) 3", "B) 4", "C) 5", "D) 6"],
    correctAnswer: "B) 4",
  },
  {
    id: 14,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi kod nima chop etadi?\n\n```python\nfor i in range(3):\n    if i == 1:\n        continue\n    print(i)\n```",
    options: ["A) 0 1 2", "B) 0 2", "C) 1 2", "D) 0 1"],
    correctAnswer: "B) 0 2",
  },
  {
    id: 15,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi kod nechta marta 'hello' chop etadi?\n\n```python\ni = 5\nwhile i > 2:\n    print('hello')\n    i -= 2\n```",
    options: ["A) 1 marta", "B) 2 marta", "C) 3 marta", "D) Cheksiz"],
    correctAnswer: "B) 2 marta",
  },
  {
    id: 16,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nx = 10\nif x > 5:\n    if x < 15:\n        print('Medium')\n    else:\n        print('Large')\nelse:\n    print('Small')\n```",
    options: ["A) Small", "B) Medium", "C) Large", "D) Error"],
    correctAnswer: "B) Medium",
  },
  {
    id: 17,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi shart bajariladimi?\n\n```python\nif 'python' in 'python programming':\n    print('Found')\n```",
    options: ["A) Ha", "B) Yo'q", "C) Xatolik beradi", "D) Faqat Python 3 da"],
    correctAnswer: "A) Ha",
  },
  {
    id: 18,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi kod nima chop etadi?\n\n```python\nscore = 85\nif score >= 90:\n    grade = 'A'\nelif score >= 80:\n    grade = 'B'\nelse:\n    grade = 'C'\nprint(grade)\n```",
    options: ["A) A", "B) B", "C) C", "D) Error"],
    correctAnswer: "B) B",
  },
  {
    id: 19,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi kod nima chiqaradi?\n\n```python\nfor i in range(5):\n    if i == 2:\n        break\n    print(i)\n```",
    options: ["A) 0 1", "B) 0 1 2", "C) 1 2", "D) 0 1 2 3 4"],
    correctAnswer: "A) 0 1",
  },
  {
    id: 20,
    category: "Shart operatorlari, sikllar, range()",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ncount = 0\nfor i in range(1, 11):\n    if i % 3 == 0:\n        count += 1\nprint(count)\n```",
    options: ["A) 2", "B) 3", "C) 4", "D) 5"],
    correctAnswer: "B) 3",
  },

  // Funksiya, argument, return, *args (21-30)
  {
    id: 21,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi funksiya nima qaytaradi?\n\n```python\ndef multiply(a, b=2):\n    return a * b\nresult = multiply(5)\n```",
    options: ["A) 5", "B) 10", "C) 7", "D) Error"],
    correctAnswer: "B) 10",
  },
  {
    id: 22,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndef power(base, exp=2):\n    return base ** exp\nprint(power(3, 3))\n```",
    options: ["A) 9", "B) 27", "C) 6", "D) 18"],
    correctAnswer: "B) 27",
  },
  {
    id: 23,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi kod chiqishini toping:\n\n```python\ndef greet(name='World'):\n    return f'Hello, {name}!'\nprint(greet())\n```",
    options: ["A) Hello!", "B) Hello, None!", "C) Hello, World!", "D) Error"],
    correctAnswer: "C) Hello, World!",
  },
  {
    id: 24,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndef sum_all(*numbers):\n    return sum(numbers)\nprint(sum_all(1, 2, 3, 4))\n```",
    options: ["A) (1, 2, 3, 4)", "B) [1, 2, 3, 4]", "C) 10", "D) Error"],
    correctAnswer: "C) 10",
  },
  {
    id: 25,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi kod chiqishini toping:\n\n```python\ndef calculate():\n    x = 10\n    y = 5\n    return x + y, x - y\nresult = calculate()\nprint(type(result))\n```",
    options: ["A) <class 'list'>", "B) <class 'tuple'>", "C) <class 'int'>", "D) <class 'str'>"],
    correctAnswer: "B) <class 'tuple'>",
  },
  {
    id: 26,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi lambda funksiya nima qiladi?\n\n```python\nsquare = lambda x: x ** 2\nprint(square(4))\n```",
    options: ["A) 8", "B) 16", "C) 4", "D) 2"],
    correctAnswer: "B) 16",
  },
  {
    id: 27,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi kodda qanday xato bor?\n\n```python\ndef divide(a, b):\n    return a / b\nprint(divide(10))\n```",
    options: ["A) SyntaxError", "B) TypeError - argument yetishmaydi", "C) ZeroDivisionError", "D) ValueError"],
    correctAnswer: "B) TypeError - argument yetishmaydi",
  },
  {
    id: 28,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndef outer(x):\n    def inner(y):\n        return x + y\n    return inner\nfunc = outer(5)\nprint(func(3))\n```",
    options: ["A) 5", "B) 3", "C) 8", "D) Error"],
    correctAnswer: "C) 8",
  },
  {
    id: 29,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndef modify_list(lst):\n    lst.append(4)\n    return lst\n\noriginal = [1, 2, 3]\nresult = modify_list(original)\nprint(len(original))\n```",
    options: ["A) 3", "B) 4", "C) Error", "D) 0"],
    correctAnswer: "B) 4",
  },
  {
    id: 30,
    category: "Funksiya, argument, return, *args",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndef factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n-1)\nprint(factorial(4))\n```",
    options: ["A) 12", "B) 24", "C) 10", "D) 16"],
    correctAnswer: "B) 24",
  },

  // String, split(), join(), map(), filter(), lambda (31-40)
  {
    id: 31,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ntext = 'Python Programming'\nprint(text.lower().title())\n```",
    options: ["A) python programming", "B) Python Programming", "C) PYTHON PROGRAMMING", "D) Python programming"],
    correctAnswer: "B) Python Programming",
  },
  {
    id: 32,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ntext = 'apple,banana,cherry'\nfruits = text.split(',')\nprint(len(fruits))\n```",
    options: ["A) 1", "B) 2", "C) 3", "D) Error"],
    correctAnswer: "C) 3",
  },
  {
    id: 33,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nwords = ['Hello', 'World', 'Python']\nresult = ' '.join(words)\nprint(result)\n```",
    options: ["A) HelloWorldPython", "B) Hello World Python", "C) Hello-World-Python", "D) ['Hello', 'World', 'Python']"],
    correctAnswer: "B) Hello World Python",
  },
  {
    id: 34,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nnumbers = [1, 2, 3, 4, 5]\nsquared = list(map(lambda x: x**2, numbers))\nprint(squared[2])\n```",
    options: ["A) 3", "B) 9", "C) 6", "D) 4"],
    correctAnswer: "B) 9",
  },
  {
    id: 35,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nnumbers = [1, 2, 3, 4, 5, 6]\neven_numbers = list(filter(lambda x: x % 2 == 0, numbers))\nprint(len(even_numbers))\n```",
    options: ["A) 2", "B) 3", "C) 4", "D) 6"],
    correctAnswer: "B) 3",
  },
  {
    id: 36,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ntext = 'Hello World'\nresult = text.replace('World', 'Python')\nprint(result)\n```",
    options: ["A) Hello World", "B) Hello Python", "C) Python World", "D) Error"],
    correctAnswer: "B) Hello Python",
  },
  {
    id: 37,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nsentence = 'Programming is fun'\nwords = sentence.split()\nprint(words[-1])\n```",
    options: ["A) Programming", "B) is", "C) fun", "D) Error"],
    correctAnswer: "C) fun",
  },
  {
    id: 38,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nname = 'Alice'\nage = 25\nmessage = f'{name} is {age} years old'\nprint(len(message))\n```",
    options: ["A) 18", "B) 19", "C) 20", "D) 21"],
    correctAnswer: "A) 18",
  },
  {
    id: 39,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ntext = 'Python'\nprint(text[1:4][::-1])\n```",
    options: ["A) yth", "B) hty", "C) Pyt", "D) thp"],
    correctAnswer: "B) hty",
  },
  {
    id: 40,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndata = ['1', '2', '3', '4']\nnumbers = list(map(int, data))\nprint(sum(numbers))\n```",
    options: ["A) 1234", "B) 10", "C) '1234'", "D) Error"],
    correctAnswer: "B) 10",
  },

  // OOP, class, inheritance, method, init (41-50)
  {
    id: 41,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nclass Person:\n    def __init__(self, name):\n        self.name = name\n    \n    def greet(self):\n        return f'Hello, I am {self.name}'\n\np = Person('Ali')\nprint(p.greet())\n```",
    options: ["A) Hello, I am Person", "B) Hello, I am Ali", "C) Ali", "D) Error"],
    correctAnswer: "B) Hello, I am Ali",
  },
  {
    id: 42,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nclass Animal:\n    def speak(self):\n        return 'Some sound'\n\nclass Dog(Animal):\n    def speak(self):\n        return 'Woof!'\n\nd = Dog()\nprint(d.speak())\n```",
    options: ["A) Some sound", "B) Woof!", "C) Animal", "D) Error"],
    correctAnswer: "B) Woof!",
  },
  {
    id: 43,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nclass Counter:\n    count = 0\n    \n    def __init__(self):\n        Counter.count += 1\n\nc1 = Counter()\nc2 = Counter()\nprint(Counter.count)\n```",
    options: ["A) 0", "B) 1", "C) 2", "D) Error"],
    correctAnswer: "C) 2",
  },
  {
    id: 44,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nclass Rectangle:\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n    \n    def area(self):\n        return self.width * self.height\n\nr = Rectangle(5, 3)\nprint(r.area())\n```",
    options: ["A) 8", "B) 15", "C) 53", "D) Error"],
    correctAnswer: "B) 15",
  },
  {
    id: 45,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nclass Parent:\n    def __init__(self):\n        self.value = 'parent'\n\nclass Child(Parent):\n    def __init__(self):\n        super().__init__()\n        self.value = 'child'\n\nc = Child()\nprint(c.value)\n```",
    options: ["A) parent", "B) child", "C) None", "D) Error"],
    correctAnswer: "B) child",
  },
  {
    id: 46,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nclass BankAccount:\n    def __init__(self, balance=0):\n        self.__balance = balance\n    \n    def get_balance(self):\n        return self.__balance\n\naccount = BankAccount(100)\nprint(account.get_balance())\n```",
    options: ["A) 0", "B) 100", "C) None", "D) Error"],
    correctAnswer: "B) 100",
  },
  
  // Kod natijasini topish savollari (47-50)
  {
    id: 47,
    category: "Kod natijasini topish",
    type: "code",
    question: "Quyidagi kodni ishga tushiring va natijasini ayting:\n\n```python\ndef mystery_function(lst):\n    result = []\n    for i in range(len(lst)):\n        if i % 2 == 0:\n            result.append(lst[i] * 2)\n        else:\n            result.append(lst[i] + 10)\n    return result\n\ndata = [1, 2, 3, 4, 5]\noutput = mystery_function(data)\nprint(output)\n```",
    options: ["A) [2, 12, 6, 14, 10]", "B) [1, 12, 3, 14, 5]", "C) [2, 2, 6, 4, 10]", "D) [11, 4, 13, 8, 15]"],
    correctAnswer: "A) [2, 12, 6, 14, 10]",
  },
  {
    id: 48,
    category: "Kod natijasini topish",
    type: "code",
    question: "Quyidagi kodni ishga tushiring va natijasini ayting:\n\n```python\nclass NumberProcessor:\n    def __init__(self):\n        self.numbers = []\n    \n    def add_number(self, num):\n        self.numbers.append(num)\n    \n    def process(self):\n        total = 0\n        for num in self.numbers:\n            if num > 5:\n                total += num ** 2\n            else:\n                total += num\n        return total\n\nprocessor = NumberProcessor()\nnumbers_to_add = [2, 6, 3, 8, 1]\n\nfor num in numbers_to_add:\n    processor.add_number(num)\n\nresult = processor.process()\nprint(result)\n```",
    options: ["A) 20", "B) 106", "C) 110", "D) 126"],
    correctAnswer: "C) 110",
  },
  {
    id: 49,
    category: "Kod natijasini topish",
    type: "code",
    question: "Quyidagi kodni ishga tushiring va natijasini ayting:\n\n```python\ndef string_manipulator(text):\n    words = text.split()\n    result = []\n    \n    for word in words:\n        if len(word) % 2 == 0:\n            result.append(word.upper())\n        else:\n            result.append(word.lower())\n    \n    return ' '.join(result)\n\ninput_text = \"Python Programming Is Fun\"\noutput = string_manipulator(input_text)\nprint(output)\n```",
    options: ["A) python programming is fun", "B) PYTHON PROGRAMMING IS fun", "C) python PROGRAMMING is fun", "D) PYTHON programming IS fun"],
    correctAnswer: "B) PYTHON PROGRAMMING IS fun",
  },
  {
    id: 50,
    category: "Kod natijasini topish",
    type: "code",
    question: "Quyidagi kodni ishga tushiring va natijasini ayting:\n\n```python\ndef fibonacci_sum(n):\n    if n <= 0:\n        return 0\n    elif n == 1:\n        return 1\n    \n    a, b = 0, 1\n    total = 1\n    \n    for i in range(2, n + 1):\n        c = a + b\n        total += c\n        a, b = b, c\n    \n    return total\n\nresult = fibonacci_sum(6)\nprint(result)\n```",
    options: ["A) 12", "B) 20", "C) 8", "D) 33"],
    correctAnswer: "B) 20",
  }
]