export const pythonQuestions = [
  // O'zgaruvchilar, ma'lumot turlari, operatorlar (1-10)
  {
    id: 1,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nx = 5\ny = '5'\nprint(x + int(y))\n```",
    options: ["A) 10", "B) 55", "C) TypeError", "D) 5"],
    correctAnswer: "A) 10",
  },
  {
    id: 2,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagilardan qaysi biri to'g'ri o'zgaruvchi nomi?",
    options: ["A) 2value", "B) value_2", "C) value-2", "D) value 2"],
    correctAnswer: "B) value_2",
  },
  {
    id: 3,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ntype([])\n```",
    options: ["A) <class 'list'>", "B) <class 'dict'>", "C) <class 'tuple'>", "D) <class 'set'>"],
    correctAnswer: "A) <class 'list'>",
  },
  {
    id: 4,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: 'Quyidagi kod natijasini toping:\n\n```python\nlen("python"[::2])\n```',
    options: ["A) 6", "B) 3", "C) 4", "D) 2"],
    correctAnswer: "B) 3",
  },
  {
    id: 5,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nnot (True and False)\n```",
    options: ["A) True", "B) False", "C) None", "D) Error"],
    correctAnswer: "A) True",
  },
  {
    id: 6,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagilardan qaysi biri set yaratiladi?",
    options: ["A) {1, 2, 3}", "B) [1, 2, 3]", "C) (1, 2, 3)", "D) {'a': 1}"],
    correctAnswer: "A) {1, 2, 3}",
  },
  {
    id: 7,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod chiqadigan qiymatni toping:\n\n```python\nprint(10 // 3)\n```",
    options: ["A) 3.33", "B) 3", "C) 4", "D) 1"],
    correctAnswer: "B) 3",
  },
  {
    id: 8,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nx = 3\nx *= 2 + 1\nprint(x)\n```",
    options: ["A) 6", "B) 7", "C) 9", "D) 11"],
    correctAnswer: "C) 9",
  },
  {
    id: 9,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nmy_tuple = (1, 2, 3)\nmy_tuple[0] = 4\n```",
    options: ["A) (4, 2, 3)", "B) [4, 2, 3]", "C) TypeError", "D) IndexError"],
    correctAnswer: "C) TypeError",
  },
  {
    id: 10,
    category: "O'zgaruvchilar, ma'lumot turlari, operatorlar",
    type: "closed",
    question: "Quyidagi kodda qanday xatolik bor?\n\n```python\nx = '5'\nprint(x + 2)\n```",
    options: ["A) SyntaxError", "B) TypeError", "C) ValueError", "D) NameError"],
    correctAnswer: "B) TypeError",
  },

  // Shart operatorlari, sikllar, range(), enumerate() (11-20)
  {
    id: 11,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "Quyidagi kod nechta son chop etadi?\n\n```python\nfor i in range(1, 5):\n    print(i)\n```",
    options: ["A) 3 ta", "B) 4 ta", "C) 5 ta", "D) 6 ta"],
    correctAnswer: "B) 4 ta",
  },
  {
    id: 12,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "Quyidagi kod bloki bajariladimi?\n\n```python\nif 0:\n    print('Hello')\n```",
    options: ["A) Ha", "B) Yo'q", "C) Xatolik beradi", "D) Faqat Python 2 da"],
    correctAnswer: "B) Yo'q",
  },
  {
    id: 13,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "Quyidagi kod nechta qiymat beradi?\n\n```python\nrange(2, 10, 3)\n```",
    options: ["A) 2", "B) 3", "C) 4", "D) 5"],
    correctAnswer: "B) 3",
  },
  {
    id: 14,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "1-100 oralig'ida 10 ga bo'linuvchi sonlarni chop etish uchun qaysi variant to'g'ri?",
    options: ["A) range(10, 101, 10)", "B) range(1, 101, 10)", "C) range(0, 100, 10)", "D) range(10, 100, 10)"],
    correctAnswer: "A) range(10, 101, 10)",
  },
  {
    id: 15,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "Quyidagi kod nechta raqam chop etadi?\n\n```python\ni = 0\nwhile i < 3:\n    print(i)\n    i += 1\n```",
    options: ["A) 2 ta", "B) 3 ta", "C) 4 ta", "D) Cheksiz"],
    correctAnswer: "B) 3 ta",
  },
  {
    id: 16,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "Quyidagi kodda infinite loop xatoligi bormi?\n\n```python\nwhile True:\n    break\n```",
    options: [
      "A) Ha, break ishlamaydi",
      "B) Yo'q, break sikl to'xtatadi",
      "C) Ha, True har doim True",
      "D) Sintaksis xato",
    ],
    correctAnswer: "B) Yo'q, break sikl to'xtatadi",
  },
  {
    id: 17,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "Quyidagi shart bajariladimi?\n\n```python\nif 3 > 2 and 1 < 4:\n    print('True')\n```",
    options: ["A) Ha", "B) Yo'q", "C) Xatolik beradi", "D) Faqat Python 3 da"],
    correctAnswer: "A) Ha",
  },
  {
    id: 18,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question:
      "Quyidagi kod nima chop etadi?\n\n```python\nx = 5\nif x != 5:\n    print('Wrong')\nelse:\n    print('Right')\n```",
    options: ["A) Wrong", "B) Right", "C) Xatolik", "D) Hech narsa"],
    correctAnswer: "B) Right",
  },
  {
    id: 19,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "Quyidagi sikl bajariladimi?\n\n```python\nwhile False:\n    print('Hello')\n```",
    options: ["A) Ha", "B) Yo'q", "C) Xatolik beradi", "D) Faqat Python 2 da"],
    correctAnswer: "B) Yo'q",
  },
  {
    id: 20,
    category: "Shart operatorlari, sikllar, range(), enumerate()",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nlist(enumerate(['a', 'b', 'c']))\n```",
    options: [
      "A) [0, 1, 2]",
      "B) ['a', 'b', 'c']",
      "C) [(0, 'a'), (1, 'b'), (2, 'c')]",
      "D) [('a', 0), ('b', 1), ('c', 2)]",
    ],
    correctAnswer: "C) [(0, 'a'), (1, 'b'), (2, 'c')]",
  },

  // Funksiya, argument, return, *args, **kwargs (21-30)
  {
    id: 21,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question:
      "Quyidagi funksiyani chaqirish uchun qaysi variant to'g'ri?\n\n```python\ndef add(x, y):\n    return x + y\n```",
    options: ["A) add(2, 3)", "B) add[2, 3]", "C) add{2, 3}", "D) add<2, 3>"],
    correctAnswer: "A) add(2, 3)",
  },
  {
    id: 22,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndef f(x):\n    return x * x\nprint(f(3))\n```",
    options: ["A) 6", "B) 9", "C) 3", "D) 12"],
    correctAnswer: "B) 9",
  },
  {
    id: 23,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question: "Quyidagi kod chiqishini toping:\n\n```python\ndef f(x=5):\n    print(x)\nf()\n```",
    options: ["A) 0", "B) None", "C) 5", "D) Error"],
    correctAnswer: "C) 5",
  },
  {
    id: 24,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndef f(*args):\n    print(args)\nf(1, 2, 3)\n```",
    options: ["A) [1, 2, 3]", "B) (1, 2, 3)", "C) {1, 2, 3}", "D) 1 2 3"],
    correctAnswer: "B) (1, 2, 3)",
  },
  {
    id: 25,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question:
      "Quyidagi kod chiqishini toping:\n\n```python\ndef say_hello():\n    return 'Hello'\nprint(say_hello())\n```",
    options: ["A) say_hello", "B) Hello", "C) None", "D) Error"],
    correctAnswer: "B) Hello",
  },
  {
    id: 26,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question: "max_of_three(a, b, c) funksiyasini yozishda qaysi variant to'g'ri?",
    options: ["A) return max(a, b, c)", "B) print max(a, b, c)", "C) max(a, b, c)", "D) return a, b, c"],
    correctAnswer: "A) return max(a, b, c)",
  },
  {
    id: 27,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\ndef f(**kwargs):\n    print(kwargs)\nf(a=1, b=2)\n```",
    options: ["A) a=1, b=2", "B) {'a': 1, 'b': 2}", "C) (a=1, b=2)", "D) [a=1, b=2]"],
    correctAnswer: "B) {'a': 1, 'b': 2}",
  },
  {
    id: 28,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question: "Quyidagi kodda qanday xato bor?\n\n```python\ndef test(x, y):\n    return x + y\nprint(test(3))\n```",
    options: ["A) SyntaxError", "B) TypeError - argument yetishmaydi", "C) ValueError", "D) Xato yo'q"],
    correctAnswer: "B) TypeError - argument yetishmaydi",
  },
  {
    id: 29,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question: "Quyidagi lambda funksiyasi qanday ishlaydi?\n\n```python\nlambda x: x * 2\n```",
    options: ["A) x ni 2 ga bo'ladi", "B) x ni 2 ga ko'paytiradi", "C) x ga 2 qo'shadi", "D) x dan 2 ayiradi"],
    correctAnswer: "B) x ni 2 ga ko'paytiradi",
  },
  {
    id: 30,
    category: "Funksiya, argument, return, *args, **kwargs",
    type: "closed",
    question:
      "Quyidagi kod natijasini toping:\n\n```python\ndef greet(name, greeting='Hello'):\n    return f'{greeting}, {name}!'\nprint(greet('Ali'))\n```",
    options: ["A) Ali, Hello!", "B) Hello, Ali!", "C) greet Ali", "D) Error"],
    correctAnswer: "B) Hello, Ali!",
  },

  // String, split(), join(), map(), filter(), lambda (31-40)
  {
    id: 31,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\n'python'.upper()\n```",
    options: ["A) Python", "B) PYTHON", "C) python", "D) PyThOn"],
    correctAnswer: "B) PYTHON",
  },
  {
    id: 32,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\n'hello world'.split()\n```",
    options: ["A) ['hello', 'world']", "B) 'hello world'", "C) ['hello world']", "D) ('hello', 'world')"],
    correctAnswer: "A) ['hello', 'world']",
  },
  {
    id: 33,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\n'-'.join(['a', 'b', 'c'])\n```",
    options: ["A) a-b-c", "B) abc", "C) a b c", "D) ['a-b-c']"],
    correctAnswer: "A) a-b-c",
  },
  {
    id: 34,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nlist(map(lambda x: x+1, [1,2,3]))\n```",
    options: ["A) [1, 2, 3]", "B) [2, 3, 4]", "C) [0, 1, 2]", "D) [1, 3, 5]"],
    correctAnswer: "B) [2, 3, 4]",
  },
  {
    id: 35,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "filter() funksiyasi nima qiladi?",
    options: [
      "A) Elementlarni o'zgartiradi",
      "B) Shartga mos elementlarni tanlaydi",
      "C) Elementlarni birlashtiradi",
      "D) Elementlarni tartiblaydi",
    ],
    correctAnswer: "B) Shartga mos elementlarni tanlaydi",
  },
  {
    id: 36,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nlist(filter(lambda x: x%2==0, range(5)))\n```",
    options: ["A) [1, 3]", "B) [0, 2, 4]", "C) [2, 4]", "D) [0, 1, 2, 3, 4]"],
    correctAnswer: "B) [0, 2, 4]",
  },
  {
    id: 37,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nx = list('abc')\nx[0] = 'z'\nprint(x)\n```",
    options: ["A) ['a', 'b', 'c']", "B) ['z', 'b', 'c']", "C) 'zbc'", "D) Error"],
    correctAnswer: "B) ['z', 'b', 'c']",
  },
  {
    id: 38,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\n'Abc'.lower().capitalize()\n```",
    options: ["A) ABC", "B) abc", "C) Abc", "D) AbC"],
    correctAnswer: "C) Abc",
  },
  {
    id: 39,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\nname = 'Ali'\nprint(f'Hello, {name}!')\n```",
    options: ["A) Hello, name!", "B) Hello, Ali!", "C) f Hello, Ali!", "D) Error"],
    correctAnswer: "B) Hello, Ali!",
  },
  {
    id: 40,
    category: "String, split(), join(), map(), filter(), lambda",
    type: "closed",
    question: "Quyidagi kod natijasini toping:\n\n```python\n'python'[::-1]\n```",
    options: ["A) python", "B) nohtyp", "C) pythno", "D) Error"],
    correctAnswer: "B) nohtyp",
  },

  // OOP, class, inheritance, method, init (41-43)
  {
    id: 41,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question:
      "Class yaratishda qaysi metod avtomatik chaqiriladi?\n\n```python\nclass Car:\n    # qaysi metod avtomatik chaqiriladi?\n```",
    options: ["A) __init__", "B) __new__", "C) __start__", "D) __create__"],
    correctAnswer: "A) __init__",
  },
  {
    id: 42,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question:
      "Quyidagi kodda nima chop etiladi?\n\n```python\nclass A:\n    def show(self):\n        print('A')\n\nclass B(A):\n    pass\n\nb = B()\nb.show()\n```",
    options: ["A) B", "B) A", "C) Error", "D) Hech narsa"],
    correctAnswer: "B) A",
  },
  {
    id: 43,
    category: "OOP, class, inheritance, method, init",
    type: "closed",
    question: "OOP da inheritance ning asosiy maqsadi nima?",
    options: ["A) Kodni takrorlash", "B) Kodni qayta ishlatish", "C) Kodni murakkablashtirish", "D) Kodni yashirish"],
    correctAnswer: "B) Kodni qayta ishlatish",
  },
]
